export const razones = [
  "Porque tu sonrisa ilumina mis días ❤️‍🩹",
  "Porque haces que todo sea más bonito ❤️‍🩹",
  "Porque me entiendes incluso cuando no hablo ❤️‍🩹",
  "Porque tus abrazos son mi lugar favorito ❤️‍🩹",
  "Porque contigo me siento en paz ❤️‍🩹",
  "Porque siempre encuentras la forma de darme tranquilidad ❤️‍🩹",
  "Porque me apoyas en mis sueños ❤️‍🩹",
  "Porque haces especiales los días normales ❤️‍🩹",
  "Porque me inspiras a ser mejor ❤️‍🩹",
  "Porque tu mirada tiene algo mágico ❤️‍🩹",
  "Porque me haces sentir amado ❤️‍🩹",
  "Porque eres mi mejor amiga ❤️‍🩹",
  "Porque siempre estás cuando te necesito ❤️‍🩹",
  "Porque me escuchas de verdad ❤️‍🩹",
  "Porque tu felicidad también es la mía ❤️‍🩹",
  "Porque haces que valga la pena cada esfuerzo ❤️‍🩹",
  "Porque contigo aprendí lo que es amar ❤️‍🩹",
  "Porque me aceptas tal como soy ❤️‍🩹",
  "Porque tus mensajes alegran mi día ❤️‍🩹",
  "Porque tu voz me tranquiliza ❤️‍🩹",
  "Porque haces que el tiempo pase volando ❤️‍🩹",
  "Porque compartes mis locuras ❤️‍🩹",
  "Porque me haces sentir importante ❤️‍🩹",
  "Porque me motivas a seguir adelante ❤️‍🩹",
  "Porque eres fuerte cuando más lo necesitas ❤️‍🩹",
  "Porque admiro tu corazón ❤️‍🩹",
  "Porque me haces creer en el amor ❤️‍🩹",
  "Porque cada recuerdo contigo vale oro ❤️‍🩹",
  "Porque eres hermosa por dentro y por fuera ❤️‍🩹",
  "Porque contigo todo tiene sentido ❤️‍🩹",
  "Porque eres única ❤️‍🩹",
  "Porque me encanta tu forma de ser ❤️‍🩹",
  "Porque me haces sentir afortunado ❤️‍🩹",
  "Porque nunca me dejas rendirme ❤️‍🩹",
  "Porque me haces sonreír sin razón ❤️‍🩹",
  "Porque eres mi tranquilidad ❤️‍🩹",
  "Porque eres mi aventura favorita ❤️‍🩹",
  "Porque me haces sentir en casa ❤️‍🩹",
  "Porque cada día contigo es diferente ❤️‍🩹",
  "Porque haces mi vida mejor ❤️‍🩹",
  "Porque tu amor me fortalece ❤️‍🩹",
  "Porque eres mi inspiración ❤️‍🩹",
  "Porque siempre encuentras algo bueno en todo ❤️‍🩹",
  "Porque me enseñas a disfrutar la vida ❤️‍🩹",
  "Porque eres paciente conmigo ❤️‍🩹",
  "Porque me haces sentir especial ❤️‍🩹",
  "Porque contigo aprendí a confiar ❤️‍🩹",
  "Porque me haces creer que todo es posible ❤️‍🩹",
  "Porque me encanta verte feliz ❤️‍🩹",
  "Porque siempre tienes algo bonito que decir ❤️‍🩹",
  "Porque haces que mi corazón lata más fuerte ❤️‍🩹",
  "Porque eres mi pensamiento favorito ❤️‍🩹",
  "Porque haces que cada momento sea memorable ❤️‍🩹",
  "Porque siempre encuentras la forma de sorprenderme ❤️‍🩹",
  "Porque contigo puedo ser yo mismo ❤️‍🩹",
  "Porque me das paz ❤️‍🩹",
  "Porque eres mi persona favorita ❤️‍🩹",
  "Porque haces que los problemas parezcan pequeños ❤️‍🩹",
  "Porque haces que me sienta completo ❤️‍🩹",
  "Porque tu amor es sincero ❤️‍🩹",
  "Porque me haces sentir seguro ❤️‍🩹",
  "Porque eres increíble ❤️‍🩹",
  "Porque me haces querer mejorar cada día ❤️‍🩹",
  "Porque compartimos sueños ❤️‍🩹",
  "Porque siempre tienes una palabra de ánimo ❤️‍🩹",
  "Porque haces que me sienta comprendido ❤️‍🩹",
  "Porque eres un regalo en mi vida ❤️‍🩹",
  "Porque haces que el amor parezca fácil ❤️‍🩹",
  "Porque siempre encuentras la forma de alegrarme ❤️‍🩹",
  "Porque tu presencia cambia mi día ❤️‍🩹",
  "Porque me encanta pasar tiempo contigo ❤️‍🩹",
  "Porque eres mi apoyo ❤️‍🩹",
  "Porque haces que los momentos simples sean especiales ❤️‍🩹",
  "Porque me haces sentir valorado ❤️‍🩹",
  "Porque tu compañía es suficiente ❤️‍🩹",
  "Porque siempre estás en mis pensamientos ❤️‍🩹",
  "Porque eres una persona maravillosa ❤️‍🩹",
  "Porque haces que quiera construir un futuro ❤️‍🩹",
  "Porque eres mi felicidad ❤️‍🩹",
  "Porque cada día descubro algo nuevo que amar de ti ❤️‍🩹",
  "Porque me haces sentir vivo ❤️‍🩹",
  "Porque me ayudas a crecer ❤️‍🩹",
  "Porque haces que todo sea más fácil ❤️‍🩹",
  "Porque eres mi lugar seguro ❤️‍🩹",
  "Porque compartimos tantos recuerdos hermosos ❤️‍🩹",
  "Porque siempre estás cuando te necesito ❤️‍🩹",
  "Porque me haces sentir amado incluso en mis peores días ❤️‍🩹",
  "Porque siempre encuentras la forma de cuidarme ❤️‍🩹",
  "Porque eres luz en mi vida ❤️‍🩹",
  "Porque me encanta tu forma de ver el mundo ❤️‍🩹",
  "Porque contigo aprendí que el amor verdadero existe ❤️‍🩹",
  "Porque cada día te elijo nuevamente ❤️‍🩹",
  "Porque sigues siendo mi persona favorita ❤️‍🩹",
  "Porque haces que mi corazón se quede contigo ❤️‍🩹",
  "Porque volvería a conocerte una y mil veces ❤️‍🩹",
  "Porque tu mirada tiene algo mágico ❤️‍🩹",
  "Porque me haces sentir amado ❤️‍🩹",
  "Porque eres mi mejor amiga ❤️‍🩹",
  "Porque me haces creer en el amor ❤️‍🩹",

  "Porque me apoyaste cuando más lo necesitaba y me dejaste solo cuando todo fue mejor 😒"
];